name: Deploy to EC2
on:
  push:
    branches: [ main ]      
  workflow_dispatch:         
# main에 push될 때만 배포
# 수동 실행 버튼(테스트용)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e                              
            cd /var/www/mysite
            git pull origin main                
            sudo nginx -t                       
            sudo systemctl reload nginx
            curl -sS -X POST "${{ secrets.WEB_HOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "type": "message",
              "attachments": [{
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {"type": "TextBlock", "text": "🚨 서버 알림", "size": "Large", "weight": "Bolder"},
                    {"type": "TextBlock", "text": "백업 작업이 완료되었습니다.", "wrap": true}
                  ]
                }
              }]
            }'
